image: $SKA_K8S_TOOLS_BUILD_DEPLOY

variables:
  GIT_SUBMODULE_STRATEGY: recursive

workflow:
  name: '$CI_PIPELINE_NAME'
  
stages:
  - lint
  - build
  - pages
  - test
  - scan
  - publish

include:

  # Python packages build, lint, test and publish
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python.gitlab-ci.yml'

  # .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

  # changelog release page
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/changelog.gitlab-ci.yml'

  # Docs pages
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

  # .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

  # Release
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'

# disable dev build job
python-build-for-development:
  rules:
    - when: never

# disable publish to gitlab until necessary to import
python-publish-to-gitlab:
  rules:
    - when: never

# Ensure doc failures are non-fatal to gitlab pipelines
docs-build:
  allow_failure: true

docs-build-rtd:
  allow_failure: true
  after_script:
    - echo "Hello!"
    - echo "$DOCS_RTD_API_TOKEN"

# allow python-test failure temporarily (for CIP-3440) until understanding of
# what python-test needs to do
python-test:
  allow_failure: true
